# where things are
source:      .
destination: ./_site
layouts_dir: ./_layouts
data_dir:    ./_data

# conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# without this we would not see future workshops
future: true

# markdown processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

include: ['_pages']

